### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by yuristsepaniuk** [akrum/MyRepository#2]
Андрей, привет!

Самое главное в этой стажировке - это код стайл. Я просмотрел твой код, к сожалению все очень плохо! Нужно срочно поработать над этим! AirBnB почитай плиз! Не трать время на extra tasks. Не будет хорошего код стайла, никто не прочитает твой код и не даст совет.

Проработай срочно все!

Thx
-Yura

**Comment by akrum** [comment]
Добрый день. Спасибо, что посмотрели. Займусь как только верну лаптоп с чистки от влаги. Вообще, лично я не соглашаюсь с некоторыми требованиями AirBnb, поэтому не хотелось бы, например, после исправления всех проблем не узнать свой код. Так я по нему хотя бы ориентируюсь

**Comment by yuristsepaniuk** [comment]
Идея AirBnB чтобы в твоем коде ориентировались все коллеги. Каждому моменту в AirBnB есть толковое объяснение. 
Повторюсь, цель стажировки, научить писать хороший код! Code Style - это первое, на что мы будем обращать внимание при устройстве на стажировку.

**Comment by yuristsepaniuk** [comment]
Андрей, привет! Я еще раз подчеркну важность момента! Плиз не трать время на vk стратегии, у тебя много проблем в код стайле. Мы еще даже твой код не почитали и вряд ли будем читать, если ситуация не изменится. Очень важно писать код такой, который смогут прочитать другие. 

Если мы видим авторизацию через vk, то мы спросим на собесе, почему нужен iframe, спросим еще какие есть с ним хакерские уязвимость и тд. Предупреждали же! Узнаем про редиректы, про single sign on. Студенты не ответят, уверяю, но раз не ответят, зачем тратить время на то, что не понятно как работает.

Делай быстрее passport-local, не трать время на бессмысленные вещи типо vk-auth, преступай срочно к code style. Отложи деплой на heroku!

P.S. делай плиз что говорим :)

**Comment by yuristsepaniuk** [comment]
Ок, в бранче можешь тусоваться :) В master только то, что требуем!

**Comment by akrum** [comment]
Да, в бранче буду тусоваться, потому что это очень прикольно, хотя непонятно. Какие-то глюки с vk. Он не хочет работать на локалхосте, а пушить каждый раз на хероку, чтобы проверить логи-- как-то неприятно. Хотя мне все равно прикольно поюзать вк, так как уже использовал авторизацию в приложении на objective-c для проигрывания музыки с вк. Code style я еще раз попытался пофиксить с помощью eslint(уже делал, свел к 13-ти ошибкам), но мне не нравится Airbnb. Можно ли другой стандарт использовать? Так вроде как есть опции Google и Facebook.....

**Comment by akrum** [comment]
Я почему-то сразу не догадался завести бранч отдельный :( Хотя потом наверное лучше будет мержить и, я точно не помню, могут объединиться коммиты с бранча с мастером.

**Comment by yuristsepaniuk** [comment]
1. юзаем airbnb
2. чтобы не пушить на хероку, тебе нужно прописать hosts на своей операционке, чтобы замапить 127.0.0.1 на blabla.news.com. Тогда dns lookup закончиться у тебя в операционке. В настройках vk укажешь blabla.news.com и все будет работать

**Comment by yuristsepaniuk** [comment]
`res.json({ checkSucceded: checkResult.verdict, forUser: iNickname, picture: flightUserService.getUserPictureURL(iNickname), thisSessionToken: checkResult.sessionToken });`

такой код в одну строчку писать нельзя

**Comment by akrum** [comment]
Спасибо

**Comment by yuristsepaniuk** [comment]
gotClickOnASign скобки { } не там стоят, должно быть if {, но не if новая строка {

**Comment by akrum** [comment]
у меня даже из-за такого часто код просто не выполнялся

**Comment by yuristsepaniuk** [comment]
Андрей, не верю, скорее всего отсутствует где-нибудь `;` и js автоматическая ; вставка не туда поставила. Поэтому code style!!!

**Comment by yuristsepaniuk** [comment]
Андрей, я перестаю вотчить твой репозиторий, ввиду игноринга моих запросов по code conventions. Все дальнейшие вопросы к преподавателям по практике плиз! 13 дней назад я создал этот тикет, вижу ты работаешь над задачей vk_auth, которую мы предупредили не делать!!! К счастью мы сделали целую лекцию по code convension, очевидно тобой проигнорировано, дед лайн по этому заданию давно прошел. Ни один сотрудник эксадел не будет вчитываться в твой код на собеседовании, его просто пропустят поставив низший бал.

**Comment by akrum** [comment]
Добрый день, Юрий. Я совсем не забыл и не игнорю ваши запросы по code style-у. Я обязательно все сделаю как надо. Но я не могу этим заниматься, пока я не сделал авторизацию через сторонние сервисы. Я не могу кинуть собою же поставленную цель нерешенной. Авторизация через сторонние сервисы для меня один из ключевых моментов в этом проекте. 
Итак, я не буду оставлять авторизацию нерешенной, но при этом я не буду забывать про code style.

**Comment by TheDropOne** [comment]
Юрий, вы конечно правы и пишете  по делу, не могли бы писать на каком то одном языке, не вворачивая английских слов, никак не относящихся к профессиональной лексике. Слова "Вотчить" и "игноринга" раздражают не меньше некрасивого кода Андрея Румянцева. Спасибо.

**Comment by yuristsepaniuk** [comment]
@TheDropOne у вас есть полное право считать что угодно. Думаю, вы очень навредили данным диалогом товарищу этого репозитория.

Успехов
-Юра

**Comment by TheDropOne** [comment]
Вы высказываете критику кода в адрес ваших студентов, при этом  обещаете некие репрессии на критику в свой адрес. Вам не кажется это странным, уважаемый лектор? 
С наилучшими пожеланиями, ваш студент, Brama apps CEO.

**Comment by akrum** [comment]
Господа, перенесите, пожалуйста, эту полемику в другое место, так как это все же гитхаб, а не место для выяснения отношений.

**Comment by yuristsepaniuk** [comment]
Куряков, CEO успешный, я передам Жанне, что Вам нужен другой лектор))) Повторюсь, я не зарабатываю тут, это чисто хобби)))

**Comment by TheDropOne** [comment]
Я не считаю вас плохим лектором, я указал на то что мне не нравится в ваших лекциях, реагировать на это какими-то репрессиями - ваше право, конечно, только какой от этого смысл? Сомневаюсь что это увеличит желание студентов выбрать компанию Exadel как место первой стажировки.
Даже если делиться знаниями это ваше хобби, лекции же проходят в рабочее время.

**Comment by yuristsepaniuk** [comment]
С завтрашнего дня будет другой лектор. Никто не просит вас выбирать компанию Exadel, существует море вариантов. Компания Exadel делится знаниями 24/7, любой студент мог легко получить совет (в любой форме, пусть даже в эмоциональной). Это не дает вам право спорить с более опытными людьми. Я закрываю нашу интересную беседу, тем не менее, спасибо Семен и Андрей за фидбеки, хотя учесть вряд ли получится, не пересечемся.

**Comment by akrum** [comment]
Хочу заметить, что я никакие отзывы не оставлял :)

**Comment by TheDropOne** [comment]
Безусловно, вы - более опытный разработчик, к сожалению не поняли что я ни слова не написал про качество кода. Весело у вас наверное митапы проходят, если только самый опытный участвует в дискуссии. 
Надеюсь все же увидимся.

**Comment by TheMostExperienced** [comment]
Юрий, вам совет, и даже не спорьте, потому что я опытнее в этом вопросе: соси жизни соки или просто соси.
